# Job Search Configuration
search_settings:
  # Time filter for recent jobs (hours)
  time_filter_hours: 24

  # Maximum results per search
  max_results_per_site: 50

  # Request delay between searches (seconds)
  request_delay: 2

# Job sites to search (ATS platforms and job boards)
job_sites:
  ats_platforms:
    - "icims.com"
    - "greenhouse.io"
    - "lever.co"
    - "jobvite.io"
    - "ashbyhq.com"
    - "smartrecruiters.com"
    - "myworkdayjobs.com"

  additional_platforms:
    - "startup.jobs"
    - "wellfound.com"
    - "builtin.com"
    - "startups.gallery"

# Default job search terms (can be overridden via CLI)
default_searches:
  - "software engineer"
  - "data scientist"
  - "product manager"

# Filtering options
filters:
  # Keyword exclusions (case-insensitive)
  exclude_keywords:
    - "on-site"
    - "in-person"
    - "hybrid"
    - "intern"
    - "internship"

  # Salary filtering (USD per year)
  salary_ranges:
    minimum: 50000
    maximum: 500000

  # Experience level filtering
  exclude_experience_levels:
    - "entry level"
    - "intern"

# Output settings
output:
  # Format options: markdown, pdf, both
  format: "both"

  # Output directory
  output_dir: "./reports"

  # Report filename template
  filename_template: "job_search_{timestamp}_{search_term}"

  # Include job description summaries
  include_summaries: true

  # Maximum summary length (characters)
  max_summary_length: 300

# Google Custom Search API settings (REQUIRED for reliable results)
# Without API credentials, the agent will return zero results
google_api:
  # Get API key from: https://developers.google.com/custom-search/v1/introduction
  # 1. Go to Google Cloud Console
  # 2. Enable Custom Search API
  # 3. Create credentials (API key)
  # 4. Restrict API key to Custom Search API (recommended)
  api_key: ""

  # Get Search Engine ID from: https://cse.google.com/cse/
  # 1. Create a new search engine
  # 2. Add sites to search (or search entire web)
  # 3. Copy the Search Engine ID
  search_engine_id: ""

  # Optional: Daily quota limit (default 100 free queries/day)
  daily_quota: 100